import { useState, useEffect } from 'react';
import { useGetSpecFile, useUpdateSpecYaml } from '../hooks/useQueries';
import { Button } from './ui/button';
import { Textarea } from './ui/textarea';
import { Skeleton } from './ui/skeleton';
import { Alert, AlertDescription } from './ui/alert';
import { Save, FileCode, FileText } from 'lucide-react';

interface FileViewerProps {
  filename: string;
  editable: boolean;
}

export default function FileViewer({ filename, editable }: FileViewerProps) {
  const { data: fileContent, isLoading, error } = useGetSpecFile(filename);
  const updateYaml = useUpdateSpecYaml();
  const [editedContent, setEditedContent] = useState('');
  const [isEditing, setIsEditing] = useState(false);

  useEffect(() => {
    if (fileContent !== undefined) {
      setEditedContent(fileContent);
    }
  }, [fileContent]);

  const handleSave = async () => {
    if (filename === 'spec.yaml') {
      await updateYaml.mutateAsync(editedContent);
      setIsEditing(false);
    }
  };

  const handleCancel = () => {
    setEditedContent(fileContent || '');
    setIsEditing(false);
  };

  if (isLoading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-8 w-full" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  if (error) {
    return (
      <Alert variant="destructive">
        <AlertDescription>
          Failed to load {filename}: {(error as Error).message}
        </AlertDescription>
      </Alert>
    );
  }

  const Icon = filename.endsWith('.yaml') ? FileCode : FileText;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Icon className="h-5 w-5 text-muted-foreground" />
          <h3 className="font-semibold">{filename}</h3>
        </div>
        {editable && !isEditing && (
          <Button onClick={() => setIsEditing(true)} variant="outline" size="sm">
            Edit
          </Button>
        )}
        {editable && isEditing && (
          <div className="flex gap-2">
            <Button onClick={handleCancel} variant="outline" size="sm">
              Cancel
            </Button>
            <Button
              onClick={handleSave}
              disabled={updateYaml.isPending || editedContent === fileContent}
              size="sm"
            >
              <Save className="mr-2 h-4 w-4" />
              {updateYaml.isPending ? 'Saving...' : 'Save & Sync'}
            </Button>
          </div>
        )}
      </div>

      {editable && isEditing ? (
        <Textarea
          value={editedContent}
          onChange={(e) => setEditedContent(e.target.value)}
          className="min-h-[400px] font-mono text-sm"
          placeholder="Enter YAML content..."
        />
      ) : (
        <div className="rounded-lg border bg-muted/30 p-4">
          <pre className="overflow-x-auto text-sm">
            <code>{fileContent || 'No content available'}</code>
          </pre>
        </div>
      )}

      {!editable && (
        <Alert>
          <AlertDescription className="text-xs">
            This file is automatically generated from spec.yaml and cannot be edited directly.
          </AlertDescription>
        </Alert>
      )}
    </div>
  );
}
