/**
 * Backend type stubs for ia-niqaw-947 (SECOINFI Grade Business Management).
 * Mirrors Candid types generated by `dfx generate backend`.
 */

export interface UserProfile {
    name: string;
    email: string;
    phone: string;
    role: UserRole;
    businessRole: BusinessRole;
    company: string;
    createdAt: bigint;
}

export enum UserRole {
    admin = 'admin',
    manager = 'manager',
    staff = 'staff',
    viewer = 'viewer',
}

export enum BusinessRole {
    owner = 'owner',
    accountant = 'accountant',
    salesRep = 'salesRep',
    support = 'support',
}

export interface Contact {
    id: string;
    name: string;
    email: string;
    phone: string;
    company: string;
    type: 'customer' | 'vendor' | 'partner';
    notes: string;
    tags: string[];
    createdAt: bigint;
    updatedAt: bigint;
}

export interface Invoice {
    id: string;
    invoiceNumber: string;
    contactId: string;
    contactName: string;
    items: InvoiceItem[];
    subtotal: number;
    tax: number;
    total: number;
    status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
    dueDate: bigint;
    createdAt: bigint;
    updatedAt: bigint;
}

export interface InvoiceItem {
    description: string;
    quantity: number;
    unitPrice: number;
    total: number;
}

export interface Product {
    id: string;
    name: string;
    description: string;
    sku: string;
    price: number;
    category: string;
    stock: number;
    active: boolean;
    imageUrl: string;
    createdAt: bigint;
}

export interface FeatureToggle {
    key: string;
    enabled: boolean;
    description: string;
}

export interface PaymentProviderConfig {
    provider: string;
    apiKey: string;
    secretKey: string;
    webhookSecret: string;
    enabled: boolean;
}

export interface StripeConfiguration {
    publishableKey: string;
    secretKey: string;
    webhookSecret: string;
}

export interface ShoppingItem {
    productId: string;
    name: string;
    price: number;
    quantity: number;
}

export interface SystemConfig {
    key: string;
    value: string;
    description: string;
}

export interface Tenant {
    id: string;
    name: string;
    domain: string;
    owner: string;
    plan: 'free' | 'pro' | 'enterprise';
    createdAt: bigint;
}

export interface SitemapPage {
    slug: string;
    pageType: 'manual' | 'system' | 'runtime';
    createdAt: bigint;
}

export interface SitemapData {
    pages: SitemapPage[];
    reservedRoutes: string[];
    runtimeControlledRoutes: string[];
    merkleRoot: { rootHash: Uint8Array; timestamp: bigint } | null;
}
