/**
 * Backend type stubs for voice-invoice-au1.
 * These mirror the Candid types generated by `dfx generate backend`.
 * In production, this file is replaced by declarations/backend/index.js.
 */

export interface UserProfile {
    name: string;
    email: string;
    phone: string;
    role: string;
    createdAt: bigint;
}

export interface Transaction {
    id: string;
    donorName: string;
    donorHash: string;
    amount: number;
    currency: string;
    type: string;
    description: string;
    cgst: number;
    sgst: number;
    exemption: number;
    trustAccountId: string;
    merkleRoot: string;
    timestamp: bigint;
}

export interface PoojaRitual {
    id: string;
    name: string;
    description: string;
    price: number;
    category: string;
    horoscopeRequired: boolean;
}

export interface TrustAccount {
    id: string;
    name: string;
    accountNumber: string;
    bankName: string;
    ifsc: string;
    beneficiary: string;
}

export interface VoiceInvoiceDraft {
    id: string;
    language: string;
    rawText: string;
    parsedItems: Array<{ name: string; amount: number; quantity: number }>;
    totalAmount: number;
    cgst: number;
    sgst: number;
    status: 'draft' | 'finalized';
    createdAt: bigint;
}

export interface MerkleProof {
    transactionId: string;
    transactionHash: string;
    proof: Uint8Array[];
    rootHash: Uint8Array;
    isValid: boolean;
}

export interface Page {
    slug: string;
    pageType: PageType;
    createdAt: bigint;
    createdBy: string;
}

export enum PageType {
    manual = 'manual',
    system = 'system',
    runtime = 'runtime',
}

export interface SitemapMerkleRoot {
    rootHash: Uint8Array;
    timestamp: bigint;
}

export interface SitemapResponse {
    pages: Page[];
    reservedRoutes: string[];
    runtimeControlledRoutes: string[];
    merkleRoot: SitemapMerkleRoot | null;
}
